# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
PS1="\u\h\w "


cd /home/sullia8/.ssh/CS1XC3
git pull
cd ~
